name: build

on: [ push, pull_request ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest ]
        build_type: [ Release, Debug ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v5

      - name: Install X11
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y xorg-dev

      - name: Configure CMake
        run: cmake -B ${{ github.workspace }}/build -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}

      - name: Build Engine
        run: cmake --build ${{ github.workspace }}/build --config ${{ matrix.build_type }} --target Snaps
      - name: Build Sandbox
        run: cmake --build ${{ github.workspace }}/build --config ${{ matrix.build_type }} --target SnapsSandbox
      - name: Build Tests
        run: cmake --build ${{ github.workspace }}/build --config ${{ matrix.build_type }} --target SnapsTests
