name: build-windows

on:
  push:
  pull_request:

jobs:
  build:
    name: Build (Windows)
    runs-on: windows-latest
    strategy:
      matrix:
        build_type: [Release, Debug]
    steps:
      - uses: actions/checkout@v5

      - name: Configure CMake
        run: |
          cmake -S . -B build -G "Visual Studio 17 2022" -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}

      - name: Build Engine
        run: cmake --build build --config ${{ matrix.build_type }} --target Snaps

      - name: Build Sandbox
        run: cmake --build build --config ${{ matrix.build_type }} --target SnapsSandbox

      - name: Build Tests
        run: cmake --build build --config ${{ matrix.build_type }} --target SnapsTests
