name: tests

on:
  push:
  pull_request:

jobs:
  build:
    name: Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        build_type: [Release]

    steps:
      - uses: actions/checkout@v5

      - name: Install dependencies (X11)
        run: |
          sudo apt-get update
          sudo apt-get install -y xorg-dev

      - name: Configure CMake
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}

      - name: Build Tests
        run: cmake --build build --config ${{ matrix.build_type }} --target SnapsTests -j

      - name: Run tests
        run: ./build/tests/SnapsTests
